pybo/views/auth_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm
from pybo.models import User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        email=form.email.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('auth/login.html', form=form)


@bp.before_app_request  # 이 애너테이션은 라우트 함수보다 먼저 실행됨.
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None  # g : 플라스크에서 제공하는 컨텍스트 변수
    else:
        g.user = User.query.get(user_id)


@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view


@bp.route('/privacy/')
def privacy():
    return render_template('auth/privacy.html')

pybo/views/profile_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm, UserLoginForm
from pybo.models import User, Question, Answer, Comment
from sqlalchemy import text

import functools

bp = Blueprint('profile', __name__, url_prefix='/profile')


# 프로필 확인
@bp.route('/base/<int:user_id>/')
def profile(user_id):
    user = User.query.get_or_404(user_id)
    if user_id != user.id:
        flash("잘못된 접근 입니다.")
        return redirect(url_for('main.index'))
    return render_template('profile/profile.html', user=user)


# 작성글 조회
@bp.route('/list/<int:user_id>/')
def profile_list(user_id):
    page = request.args.get('page', type=int, default=1)        # 페이지
    user = User.query.get_or_404(user_id)
    if user_id != user.id:
        flash("잘못된 접근 입니다.")
        return redirect(url_for('main.index'))
    my_list = Question.query.where(Question.user_id == user.id).order_by(Question.create_date.desc())   # 내가 쓴 글만 가져와 작성일자가 최신인 순으로 정렬
    my_list = my_list.paginate(page, per_page=10)
    return render_template('profile/profile_list.html', my_list=my_list, user=user, page=page)


# 답글 조회
@bp.route('/answer/<int:user_id>/')
def answer_list(user_id):
    page = request.args.get('page', type=int, default=1)
    user = User.query.get_or_404(user_id)
    if user_id != user.id:
        flash("잘못된 접근 입니다.")
        return redirect(url_for('main.index'))
    my_answer = Answer.query.where(Answer.user_id == user.id).order_by(Answer.create_date.desc())   # 내가 쓴 답글만 가져와 작성일자가 최신인 순으로 정렬
    my_answer = my_answer.paginate(page, per_page=10)
    return render_template('profile/answer_list.html', my_answer=my_answer, user=user, page=page)


# 댓글 조회
@bp.route('/comment/<int:user_id>/')
def comment_list(user_id):
    page = request.args.get('page', type=int, default=1)
    user = User.query.get_or_404(user_id)
    if user_id != user.id:
        flash("잘못된 접근 입니다.")
        return redirect(url_for('main.index'))
    my_comment = Comment.query.where(Comment.user_id == user.id).order_by(Comment.create_date.desc())   # 내가 쓴 답글만 가져와 작성일자가 최신인 순으로 정렬
    my_comment = my_comment.paginate(page, per_page=10)
    return render_template('profile/comment_list.html', my_comment=my_comment, user=user, page=page)

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <!-- pybo CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- Font Awesome JS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"> <!--CDN 링크 -->
    <title>Pybo</title>
</head>
<body>
<!-- 네비게이션바 html을 include -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS-->
<script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
<!-- Bootstrap JS-->
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
<footer class="footer">
    <div class="container mt-3">
        <span class="text-muted">©2022 • JERRYPYBO.SHOP </span>
        <div class="float-right small"><a href="{{ url_for('auth.privacy') }}">개인정보취급방침</a></div>
    </div>
</footer>
</html>

pybo/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong> : {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

pybo/templates/myProfileNavbar.html
<h5 class="border-bottom pb-2 mb-3">{{ user.username }}</h5>
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" href="{{ url_for('profile.profile', user_id=g.user.id) }}">기본정보</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('profile.profile_list', user_id=g.user.id) }}">게시</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('profile.answer_list', user_id=g.user.id) }}">답변</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('profile.comment_list', user_id=g.user.id) }}">댓글</a>
    </li>
</ul>

pybo/templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('profile.profile', user_id=g.user.id) }}">내 정보 확인</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">{{ g.user.username }} (로그아웃)</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>